/**
 * Static Website Exporter for Fleet-Booking Portals
 * Packages any client portal into a 100% self-contained, pre-rendered,
 * zero-server-dependency ZIP archive that can be hosted anywhere.
 */

const fs = require('fs');
const path = require('path');
const JSZip = require('jszip');
const generator = require('./generator');

const ROOT_DIR = __dirname;

/**
 * Recursively add directory files to a JSZip folder
 * @param {JSZip} zipFolder 
 * @param {string} fsDirPath 
 */
function addDirToZip(zipFolder, fsDirPath) {
  if (!fs.existsSync(fsDirPath)) return;
  const entries = fs.readdirSync(fsDirPath, { withFileTypes: true });

  for (const entry of entries) {
    // Skip hidden files, system files, dev caches
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;

    const fullPath = path.join(fsDirPath, entry.name);
    if (entry.isDirectory()) {
      const subFolder = zipFolder.folder(entry.name);
      addDirToZip(subFolder, fullPath);
    } else if (entry.isFile()) {
      const fileBuffer = fs.readFileSync(fullPath);
      zipFolder.file(entry.name, fileBuffer);
    }
  }
}

/**
 * Generate a customized PWA Web Manifest tailored to client brand
 * @param {object} cfg
 * @returns {string} Formatted JSON string
 */
function generateManifest(cfg) {
  const brandName = (cfg.brand?.name || 'Booking Portal').trim();
  const shortName = (cfg.brand?.shortName || brandName).trim();
  const tagline = (cfg.brand?.tagline || 'Book reliable travel and taxi services').trim();
  const isTravel = cfg.template === 'travel';
  const defaultIcon = isTravel ? 'assets/logo-travel.svg' : 'assets/logo-taxi.svg';
  const logoUrl = (cfg.brand?.logoUrl && !cfg.brand.logoUrl.startsWith('data:')) ? cfg.brand.logoUrl : defaultIcon;
  const primaryColor = cfg.brand?.theme?.primary || (isTravel ? '#0284C7' : '#FFD900');
  const bgColor = cfg.brand?.theme?.background || '#0F172A';

  const manifestObj = {
    id: './',
    name: brandName,
    short_name: shortName,
    description: tagline,
    lang: 'en-IN',
    start_url: './',
    scope: './',
    display: 'standalone',
    display_override: ['standalone', 'minimal-ui'],
    orientation: 'portrait',
    background_color: bgColor,
    theme_color: primaryColor,
    categories: ['travel', 'business'],
    icons: [
      {
        src: logoUrl,
        sizes: '192x192 512x512',
        type: 'image/svg+xml',
        purpose: 'any maskable'
      }
    ],
    shortcuts: [
      {
        name: isTravel ? 'Enquire Tour' : 'Book Taxi Now',
        short_name: isTravel ? 'Tour Inquiry' : 'Book Taxi',
        description: isTravel ? 'Quick travel & tour enquiry' : 'Quick taxi booking form',
        url: './#bookingCard',
        icons: [
          {
            src: logoUrl,
            sizes: '192x192',
            type: 'image/svg+xml'
          }
        ]
      }
    ]
  };

  return JSON.stringify(manifestObj, null, 2);
}

/**
 * Generate README with instant hosting guides
 * @param {string} slug
 * @param {object} cfg
 * @returns {string}
 */
function generateReadme(slug, cfg) {
  const brandName = cfg.brand?.name || 'Travel & Taxi Portal';
  return `# ${brandName} - Standalone Website Package

This is your complete, self-contained, pre-rendered website generated by **Davlabs Fleet & Travel Portal Studio**.

It has **zero database requirements**, **zero backend server dependencies**, loads with **0ms latency**, and can be hosted on **ANY** static web host, CDN, or server worldwide.

---

## 🚀 Instant Deployment Options (Free & 100% Compatible)

### 1. Netlify Drop (Easiest - 10 Seconds)
1. Visit **[https://app.netlify.com/drop](https://app.netlify.com/drop)** in your web browser.
2. Drag and drop this extracted folder (or the \`.zip\` file directly).
3. Your website is instantly live on a secure HTTPS link with free SSL!

### 2. Vercel
1. Install Vercel CLI: \`npm install -g vercel\`
2. Run \`vercel\` in this folder and follow the prompts.
3. Or drag this folder into your GitHub repo and import it on [vercel.com](https://vercel.com).

### 3. GitHub Pages
1. Create a new repository on [GitHub](https://github.com/new).
2. Upload all the files from this folder.
3. In your repository, go to **Settings** > **Pages**.
4. Under **Branch**, select \`main\` (or \`master\`) and root \`/\`, then click **Save**.
5. Your website will be live at \`https://<your-username>.github.io/<repo-name>/\`.

### 4. Cloudflare Pages
1. Log in to the [Cloudflare Dashboard](https://dash.cloudflare.com/) and go to **Pages**.
2. Click **Create a project** > **Direct Upload**.
3. Upload this folder. Cloudflare will deploy it instantly to hundreds of edge data centers worldwide.

### 5. Traditional Web Hosting (cPanel / Hostinger / GoDaddy / Bluehost / Apache / Nginx)
1. Open your hosting control panel's **File Manager** or connect via **FTP / SFTP**.
2. Navigate to your website's public directory (usually \`public_html\` or \`www\`).
3. Upload and extract all files so \`index.html\` is at the root.

### 6. Local Offline Testing
- You can simply **double-click \`index.html\`** to open it directly in any browser!
- Or start a quick local preview server using:
  \`\`\`bash
  # Using Node.js
  npx serve .
  
  # Or using Python 3
  python3 -m http.server 8080
  \`\`\`

---

## 📁 Package Contents

| File / Folder | Purpose |
|---|---|
| \`index.html\` | Pre-rendered static landing page with embedded tokens & instant hydration |
| \`config.json\` | Client configuration backup |
| \`manifest.json\` | Progressive Web App (PWA) manifest for Add-to-Home-Screen support |
| \`service-worker.js\` | Offline cache worker for offline functionality |
| \`style.css\` | Master stylesheet bundle |
| \`css/\` | Design tokens, components, and template stylesheets |
| \`js/\` | Modular portal engine, booking controllers, and interaction logic |
| \`assets/\` | Logos, SVG badges, and graphic assets |
| \`.nojekyll\` | Ensures GitHub Pages serves all assets without Jekyll filtering |

---
Generated by Davlabs Portal Studio • All rights reserved.
`;
}

/**
 * Build a complete static website ZIP package
 * @param {string} slug - Client slug
 * @param {object} config - Client configuration object
 * @returns {Promise<Buffer>} ZIP file binary buffer
 */
async function buildWebsiteZip(slug, config) {
  if (!slug) slug = 'website';
  if (!config) throw new Error('Missing configuration data for ZIP export');

  const zip = new JSZip();

  // 1. Generate standalone pre-rendered HTML (no server base href)
  const staticHtml = generator.generateStaticHtml(slug, config, { standalone: true });
  zip.file('index.html', staticHtml);

  // 2. Client configuration JSON
  zip.file('config.json', JSON.stringify(config, null, 2));

  // 3. Tailored PWA Manifest
  zip.file('manifest.json', generateManifest(config));

  // 4. GitHub Pages .nojekyll flag
  zip.file('.nojekyll', '');

  // 5. Friendly README with hosting instructions
  zip.file('README.md', generateReadme(slug, config));

  // 6. Master style.css
  const styleCssPath = path.join(ROOT_DIR, 'style.css');
  if (fs.existsSync(styleCssPath)) {
    zip.file('style.css', fs.readFileSync(styleCssPath, 'utf8'));
  }

  // 7. Service Worker
  const swPath = path.join(ROOT_DIR, 'service-worker.js');
  if (fs.existsSync(swPath)) {
    zip.file('service-worker.js', fs.readFileSync(swPath, 'utf8'));
  }

  // 8. CSS Directory (tokens, components, taxi, travel)
  const cssFolder = zip.folder('css');
  const cssFiles = ['tokens.css', 'components.css', 'taxi.css', 'travel.css'];
  cssFiles.forEach(file => {
    const filePath = path.join(ROOT_DIR, 'css', file);
    if (fs.existsSync(filePath)) {
      cssFolder.file(file, fs.readFileSync(filePath, 'utf8'));
    }
  });

  // 9. JS Directory (app.js, taxi.js, travel.js)
  const jsFolder = zip.folder('js');
  const jsFiles = ['app.js', 'taxi.js', 'travel.js'];
  jsFiles.forEach(file => {
    const filePath = path.join(ROOT_DIR, 'js', file);
    if (fs.existsSync(filePath)) {
      jsFolder.file(file, fs.readFileSync(filePath, 'utf8'));
    }
  });

  // 10. Assets Directory (all SVGs, logos, custom logos)
  const assetsFolder = zip.folder('assets');
  const assetsDir = path.join(ROOT_DIR, 'assets');
  addDirToZip(assetsFolder, assetsDir);

  // Generate the ZIP buffer with max compression
  const zipBuffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });

  return zipBuffer;
}

module.exports = {
  buildWebsiteZip
};
